<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RNG7BRA" failures="0" tests="11" name="test.LoginTest" time="74.955" errors="1" timestamp="2022-03-15T18:40:06 IST" skipped="0">
  <testcase classname="test.LoginTest" name="open_the_LoginPage_Url" time="40.420"/>
  <testcase classname="test.LoginTest" name="enter_valid_username_and_invalid_password" time="4.767"/>
  <testcase classname="test.LoginTest" name="enter_invalid_username_and_valid_password" time="4.217"/>
  <testcase classname="test.LoginTest" name="enter_valid_username_and_empty_password" time="4.194"/>
  <testcase classname="test.LoginTest" name="enter_invalid_username_and_empty_password" time="4.167"/>
  <testcase classname="test.LoginTest" name="enter_empty_username_and_valid_password" time="4.167"/>
  <testcase classname="test.LoginTest" name="enter_empty_username_and_invalid_password" time="4.182"/>
  <testcase classname="test.LoginTest" name="enter_empty_username_and_empty_password" time="4.171"/>
  <testcase classname="test.LoginTest" name="enter_invalid_username_and_invalid_password" time="4.209"/>
  <testcase classname="test.LoginTest" name="enter_valid_username_and_valid_password" time="0.195">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Sheet.getRow(int)&quot; because the return value of &quot;org.apache.poi.ss.usermodel.Workbook.getSheet(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because the return value of "org.apache.poi.ss.usermodel.Workbook.getSheet(String)" is null
at test.LoginTest.enter_valid_username_and_valid_password(LoginTest.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- enter_valid_username_and_valid_password -->
  <testcase classname="test.LoginTest" name="enter_valid_username_and_invalid_password1" time="0.266"/>
</testsuite> <!-- test.LoginTest -->
